projects:
  life-achievements:
    schemaPath: generated/schema.prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: generated/autocomplete.prisma.ts
      endpoints:
        default: 'http://localhost:4466/'
